<?xml version='1.0' encoding='UTF-8'?>
<definitions name="exemple" targetNamespace="urn:exemple" xmlns:typens="urn:exemple" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"  xmlns:typens0="http://localhost/tp_soap/conn.php">
    <message name="dbConn"/>
    <message name="dbConnResponse">
        <part name="dbConnReturn"/>
    </message>
    <message name="recettes"/>
    <message name="recettesResponse">
        <part name="recettesReturn"/>
    </message>
    <portType name="essai_instancePortType">
        <operation name="dbConn">
            <input message="typens:dbConn"/>
            <output message="typens:dbConnResponse"/>
        </operation>
        <operation name="recettes">
            <input message="typens:recettes"/>
            <output message="typens:recettesResponse"/>
        </operation>
    </portType>
    <binding name="essai_instanceBinding" type="typens:essai_instancePortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="dbConn">
            <soap:operation soapAction="urn:essai_instanceAction"/>
            <input>
                <soap:body namespace="urn:exemple" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body namespace="urn:exemple" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
        <operation name="recettes">
            <soap:operation soapAction="urn:essai_instanceAction"/>
            <input>
                <soap:body namespace="urn:exemple" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body namespace="urn:exemple" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>
    <service name="exempleService">
        <port name="essai_instancePort" binding="typens:essai_instanceBinding">
            <soap:address location="http://localhost/tp_soap/conn.php"/>
        </port>
    </service>
</definitions>